name: CDE Menu Download

on:
  schedule:
    # Times are in UTC. Paris is UTC+1 (Winter).
    - cron: '0 8 * * 1' # Mon 09:00 Paris
    - cron: '0 7 * * 4' # Thu 08:00 Paris
    - cron: '0 7 * * 5' # Fri 08:00 Paris
  workflow_dispatch: # Allows manual trigger in the Actions tab

jobs:
  download-pdf:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run CDE Script
        shell: pwsh
        run: tools/cde.ps1

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          # This name appears in the GitHub UI
          name: Daily_Menu_PDF
          # Points specifically to the file in the root
          path: menu_cde_*.pdf
          if-no-files-found: error
          retention-days: 5