name: CDE Menu Download

on:
  schedule:
    # Paris Time (UTC+1 Winter)
    - cron: '0 8 * * 1' # Monday 09:00 Paris
    - cron: '0 7 * * 4' # Thursday 08:00 Paris
    - cron: '0 7 * * 5' # Friday 08:00 Paris
  workflow_dispatch: # This enables the "Run workflow" button manually

jobs:
  download-job:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run CDE Script
        shell: pwsh
        run: tools/cde.ps1

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          # This names the artifact download in the UI
          name: cde-menu-pdf
          # This picks up the specific file named menu_cde_YYYY-MM-DD.pdf
          path: downloads/menu_cde_*.pdf
          retention-days: 5