name: Skybroc v0.15

on: 
  schedule:
    - cron: '0 3 * * 1'
    - cron: '30 4 * * *'
    - cron: '0 9 * * 5'
  workflow_dispatch:
    inputs:
      master_url:
        description: "Provide MASTER_URL for brocabrac.fr"
        required: true
        type: string

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1.Checkout code
        uses: actions/checkout@v4

      - name: 2.Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 3.Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 4.Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: 5.Run SkyBroc
        env:
          JSONHOSTING_EDIT_KEY: ${{ secrets.JSONHOSTING_EDIT_KEY }}
          MASTER_URL: ${{ github.event.inputs.master_url }}
        run: python tools/skybroc.py
