name: SkyScraper v2025.11.17.1

on:
  schedule:
    - cron: '0 3 * * 1'
    - cron: '30 4 * * *'
    - cron: '0 9 * * 5'
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      master_url:
        description: "Provide MASTER_URL string for the scraper"
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 1.Checkout repository
        uses: actions/checkout@v4

      - name: 2.Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3.Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 4.Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m playwright install --with-deps

      - name: 5.List repository files
        run: |
          echo "Current directory:"
          pwd
          echo "Files here:"
          ls -R

      - name: 6.Check EDIT_KEY
        env:
          EDIT_KEY: ${{ secrets.JSONHOST_EDIT_KEY }}
        run: |
          echo "Checking EDIT_KEY environment variable..."
          if [ -z "$EDIT_KEY" ]; then
            echo "EDIT_KEY is missing or empty"
            exit 1
          fi
          echo "EDIT_KEY is present"

      - name: 7.Run SkyScra
        env:
          EDIT_KEY: ${{ secrets.JSONHOST_EDIT_KEY }}
          MASTER_URL: ${{ github.event.inputs.master_url }}
        run: python skyscra.py
